### ISSUE TITLE
Use unlogged abundances when taking the mean

### ISSUE THREAD

**Issue by nhinkel** [HypatiaOrg/HySite#3]
From Austin Ware (Patrick Young's student): The proper way to take the mean would be to un-log the abundances first. However, right now on Hypatia the mean is taken in log-space. So, the unlogged abundance values would need to be added to the internal mean (in output_star_data) and the calculated mean on the website.

Additional info: "I only ask because the SPORES Catalog (https://iopscience.iop.org/article/10.3847/1538-4365/ad3e81) report the mean abundances for the ExEP HWO stars, but definitely seem to be taking the mean of the log values. This results in the abundances reported being generally skewed negative, some egregiously so. I noticed that this seems to also be what Hypatia does, which has left me more confused about what is actually correct."

**Comment by chw3k5** [comment]
Fixed in these two commits:
https://github.com/HypatiaOrg/HySite/commit/442119d38b993c491866a5c28fd7d6dab90ed8af
https://github.com/HypatiaOrg/HySite/commit/4701df693e3ead90d8355c967afa4bab4e9a6a22
